name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    # - name: Install dependencies
    #   run: |
    #     pip install pipenv
    - uses: VaultVulp/action-pipenv@v1.0.0
      args: |
        pipenv install --dev --ignore-pipfile
        pipenv shell
    - name: Test with pytest
      run: |
        pytest
